from __future__ import annotations
from typing import Any, Sequence, Union, overload
import numpy as np

class DType:
    name: str
    itemsize: int
    def __repr__(self) -> str: ...

# dtype singletons
f32: DType
f64: DType
i32: DType
i64: DType
bool: DType  # exposed as bool_ in python due to keyword
bool_: DType

class Array:
    shape: tuple[int, ...]
    strides: tuple[int, ...]
    ndim: int
    size: int
    dtype: DType
    nbytes: int
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __array__(self, dtype: Any = ...) -> np.ndarray: ...
    def __buffer__(self, flags: int) -> memoryview: ...
    def __matmul__(self, other: Array) -> Array: ...
    def __rmatmul__(self, other: Array) -> Array: ...
    def __add__(self, other: Array | int | float) -> Array: ...
    def __radd__(self, other: Array | int | float) -> Array: ...
    def __sub__(self, other: Array | int | float) -> Array: ...
    def __rsub__(self, other: Array | int | float) -> Array: ...
    def __mul__(self, other: Array | int | float) -> Array: ...
    def __rmul__(self, other: Array | int | float) -> Array: ...
    def __truediv__(self, other: Array | int | float) -> Array: ...
    def __rtruediv__(self, other: Array | int | float) -> Array: ...
    def __eq__(self, other: object) -> Array: ...  # returns bool Array
    def __ne__(self, other: object) -> Array: ...
    def __getitem__(self, key: Any) -> Any: ...
    def __setitem__(self, key: Any, value: Any) -> None: ...
    def astype(self, dtype: DType) -> Array: ...
    def to_numpy(self) -> np.ndarray: ...
    def copy(self) -> Array: ...

class CsrMatrix:
    shape: tuple[int, int]
    nnz: int
    def to_dense(self) -> Array: ...
    def matvec(self, x: Array) -> Array: ...
    def matmul(self, other: CsrMatrix) -> CsrMatrix: ...

class CscMatrix:
    shape: tuple[int, int]
    nnz: int
    def to_dense(self) -> Array: ...
    def matvec(self, x: Array) -> Array: ...

# creation
def array(obj: Any, dtype: DType | None = ...) -> Array: ...
def asarray(obj: Any, dtype: DType | None = ...) -> Array: ...
def zeros(shape: int | Sequence[int], dtype: DType = ...) -> Array: ...
def ones(shape: int | Sequence[int], dtype: DType = ...) -> Array: ...
def empty(shape: int | Sequence[int], dtype: DType = ...) -> Array: ...
def full(shape: int | Sequence[int], fill_value: Any, dtype: DType | None = ...) -> Array: ...
def arange(start: Any, stop: Any | None = ..., step: Any = ..., dtype: DType | None = ...) -> Array: ...

# linalg
def matmul(a: Array, b: Array) -> Array: ...
def matvec(a: Array, b: Array) -> Array: ...
def dot(a: Array, b: Array) -> Any: ...
def norm(a: Array, ord: int | None = ...) -> float: ...
def diagonal(a: Array) -> Array: ...
def diag(v: Array) -> Array: ...
def lu(a: Array) -> tuple[Array, Array, Array]: ...
def qr(a: Array) -> tuple[Array, Array]: ...
def cholesky(a: Array) -> Array: ...
def svd(a: Array, full_matrices: bool = ...) -> tuple[Array, Array, Array]: ...
def eig(a: Array) -> tuple[Array, Array]: ...
def solve(a: Array, b: Array) -> Array: ...
def inv(a: Array) -> Array: ...
def inverse(a: Array) -> Array: ...
def det(a: Array) -> Any: ...
def determinant(a: Array) -> Any: ...
def rank(a: Array, tol: float | None = ...) -> int: ...
def cg_solve(a: CsrMatrix | Array, b: Array, tol: float = ..., max_iter: int = ...) -> Array: ...

__version__: str
